%  OBLATESPHEROID - Simulations of oblated spheroids in a plane wave

particle = Particle( ...
  'brownian', false, ...
  'halfAxes', [ 50, 50, 1 ], ...
  'pos', [0, 0, 0], ...
  'rot', [2*pi/8, 0, 0]);

trajectory = Trajectory( particle );
trajectory = trajectory.options( ...
  'lambda', 650, ...
  'dt', 0.05, ...
  'end_t', 2, ...
  'pol', [ 1, 0, 0 ], ...
  'dir', [ 0, 0, 1 ]);

trajectory = trajectory.simulate();
trajectory.visualizePlot3();
