%  OBLATESPHEROID - Simulations of oblated spheroids in a plane wave

n = 10;

particles = Particle.empty(n, 0);
angles = linspace(0, pi/2, n);

for i = 1:n
  particles(i) = Particle( ...
    'brownian', false, ...
    'halfAxes', [ 50, 50, 1 ], ...
    'pos', [0, 0, 0], ...
    'rot', [0, 0, angles(i)]);
end

sim = Simulation( particles );
sim = sim.options( ...
  'lambda', 650, ...
  'dt', 0.05, ...
  'end_t', 2, ...
  'pol', [ 1, 0, 0 ], ...
  'dir', [ 0, 0, 1 ]);

sim = sim.start();
sim.visualizePlot3();
