%  SINGLETRAJETORY - Simulation of the trajetory of a single ellipsoid 
%  in a plane wave

t = 0:0.05:2;

startPosRots = [10e3; 0; -1000e3; 0; 0; 0];
exc = galerkin.planewave( [1, 0, 0], [0, 0, 1] );
% exc = laguerregauss( Constants.w0, [1 ,0] );
sim = Simulation( ...
  'brownian', false, ...
  'halfAxes', 500*[ 1, 1, 1 ], ...
  'posRots', startPosRots, ...
  'flow', Constants.v_fluid * [0, 0, 1], ...
  't', t, ...
  'exc', exc);

sim = sim.start();
sim.visualizePlot3();
