%  SINGLETRAJETORY - Simulation of the trajetory of a single ellipsoid 
%  in a plane wave

n = 1;
particle = Particle( ...
  'brownian', false, ...
  'halfAxes', 500*[ 1, 1, 1 ], ...
  'pos', [10e3, 0, -1000e3], ...
  'rot', [0, 0, 0]);

exc = galerkin.planewave( [1, 0, 0], [0, 0, 1] );
sim = Simulation( particle );
sim = sim.options( ...
  'lambda', 650, ...
  'dt', 0.05, ...
  'end_t', 2, ...
  'exc', exc);

sim = sim.start();
sim.visualizePlot3();
